all:
	g++ -std=c++17 staticBinBallotDefault.cpp -o staticBinDef -lpthread -O3 -g
	g++ -std=c++17 staticBinBallotSCV.cpp     -o staticBinSCV -lpthread -O3 -g

clean:
	rm -rf *o staticBinDef staticBinSCV
