all:
	g++ -std=c++17 staticBinAuctionDefault.cpp -o staticBinDef -lpthread -O3 -g
	g++ -std=c++17 staticBinAuctionSCV.cpp     -o staticBinSCV -lpthread -O3 -g

clean:
	rm -rf *o staticBinDef staticBinSCV
