all:
	g++ -std=c++17 decCoinDefault.cpp  -o decDef  -lpthread -O3 -g
	g++ -std=c++17 decCoinSCV.cpp      -o decSCV  -lpthread -O3 -g
	g++ -std=c++17 forkCoinDefault.cpp -o forCDef -lpthread -O3 -g
	g++ -std=c++17 forkCoinSCV.cpp     -o forkSCV -lpthread -O3 -g

clean:
	rm -rf *o decDef forkDef decSCV forkSCV
