all:
	g++ -std=c++17 decAuctionDefault.cpp  -o decDef  -lpthread -O3 -g
	g++ -std=c++17 decAuctionSCV.cpp      -o decSCV  -lpthread -O3 -g
	g++ -std=c++17 forkAuctionDefault.cpp -o forkDef -lpthread -O3 -g
	g++ -std=c++17 forkAuctionSCV.cpp     -o forkSCV -lpthread -O3 -g

clean:
	rm -rf *o decDef forkDef decSCV forkSCV
